[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=77", "setuptools_scm>=9"]

[dependency-groups]
dev = [
  "coverage[toml]>=7.13.1",
  "pytest>=9.0.2",
  "ty>=0.0.13",
]

[project]
name = "easyspeak"
dynamic = ["version"]
description = "Voice control for Linux desktops. Fully local, no cloud, Wayland-native."
license = "GPL-3.0-only"
license-files = ["LICENSE"]
authors = [
  {name = "Matt Hartley", email = "matt@matthartley.com"},
]
maintainers = [
  {name = "Matt Hartley", email = "matt@matthartley.com"},
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Topic :: Desktop Environment :: Gnome",
  "Topic :: Home Automation",
  "Topic :: Scientific/Engineering :: Human Machine Interfaces",
  "Topic :: Utilities",
]
keywords = [
  "control",
  "desktop",
  "gnome",
  "offline",
  "voice",
  "wayland",
]
readme = "README.md"
requires-python = ">=3.10, <3.13"
dependencies = [
  "faster-whisper>=1.2.1",
  "numpy>=2.2.6",
  "openwakeword",
]

[project.scripts]
easyspeak = "easyspeak.core.main:main"

[project.urls]
"Source Code" = "https://github.com/ctsdownloads/easyspeak"

[tool.coverage.report]
exclude_also = ["if __name__ == .__main__.:"]
show_missing = true

[tool.coverage.run]
source = ["src"]

[tool.ruff.lint]
# extend-select = ["ALL"]
extend-ignore = ["D", "E722"]

[tool.setuptools.package-dir]
easyspeak = "src"

[tool.setuptools_scm]
local_scheme = "no-local-version"

[tool.uv.sources]
openwakeword = { git = "https://github.com/dscripka/openWakeWord" }
